### ISSUE TITLE
底部导航栏会覆盖在页面上方

### ISSUE THREAD

**Issue by vds2000** [luckybilly/SmartSwipe#10]
你好, 在带有系统底部导航栏的手机上，使用SmartSwipe库后，会出现导航栏覆盖在页面上。
实际效果应该是页面在系统导航栏的上方

**Comment by luckybilly** [comment]
@vds2000 请问能不能说的更详细点呢？
比如：使用的是什么功能？在什么设备上？ 
如果能放一张截图就更好了

**Comment by vds2000** [comment]
小米6X 9.0 
![Screenshot_2019-07-23-11-30-16-204_com wd myappstructure](https://user-images.githubusercontent.com/3346631/61680814-88213a00-ad3d-11e9-8a7e-daaab49ca0b1.png)
![Screenshot_2019-07-23-11-33-37-347_com wd myappstructure](https://user-images.githubusercontent.com/3346631/61680922-febe3780-ad3d-11e9-9457-0b1c2d97df29.png)

用的是底部tabLayout + viewPager + fragment
第一张截图是未使用沉浸式
第二张截图是使用了沉浸式

**Comment by Nuyoah965** [comment]
@luckybilly在1.0.1版本上会出现上图重叠现象，1.0.0版本未复现

**Comment by luckybilly** [comment]
@vds2000 @fyb070912 烦请验证一下v1.0.2版是否已修复这个问题

**Comment by Nuyoah965** [comment]
@vds2000 @luckybilly
 SmartSwipe 1.0.2
华为MT7-TL10  EMUI系统4.0
Android版本6.0
复测v1.0.2版本未出现上图重叠现象，谢谢

**Comment by luckybilly** [comment]
@fyb070912 感谢验证，后续使用中遇到其它问题也请及时反馈哈！

**Comment by Nuyoah965** [comment]
@luckybilly 好的，谢谢大佬。

**Comment by vds2000** [comment]
@luckybilly 刚测试了下，发现还是会有问题，我想是不是因为我用了androidX的关系？这边似乎未更新androidX的版本，请劳烦看下，谢谢

**Comment by luckybilly** [comment]
@vds2000 跟androidX无关，demo用的就是androidX。 你用的是v1.0.2吗

**Comment by luckybilly** [comment]
@vds2000 `smart-swipe-support`和`smart-swipe-x`是为了兼容5.0以下的嵌套滑动(NestedScrolling)而设置的扩展包，对核心逻辑无影响

**Comment by vds2000** [comment]
swipe_version 1.0.2  swipeX_version 1.0.0 swipe_support_version 1.0.0
gradle引入版本是这样的，三个都引入
是否有误？

**Comment by vds2000** [comment]
@luckybilly 目前的情况下，依旧是上次截图的样子

**Comment by luckybilly** [comment]
> swipe_version 1.0.2 swipeX_version 1.0.0 swipe_support_version 1.0.0
> gradle引入版本是这样的，三个都引入
> 是否有误？

@vds2000 不要三个都引入，根据项目使用的是support还是androidX引入不同的包

![image](https://user-images.githubusercontent.com/4155835/61779748-d57fd300-ae33-11e9-80e1-410693fe548c.png)

**Comment by luckybilly** [comment]
> @luckybilly 目前的情况下，依旧是上次截图的样子

使用的是什么功能？把使用的代码贴一下吧

**Comment by Nuyoah965** [comment]
@vds2000 @luckybilly 

![C`W1}V7ZJYP)AH O%LX4)U](https://user-images.githubusercontent.com/27824757/61780700-92befa80-ae35-11e9-8f69-62051619f527.png)
华为MT7-TL10 EMUI系统4.0
Android版本6.0
版本
 implementation 'com.billy.android:smart-swipe:1.0.2'
 implementation 'com.billy.android:smart-swipe-support:1.0.0'

沉浸式使用的是:com.gyf.immersionbar:immersionbar:2.3.3-beta15,上图是使用后的现象，未发现重叠呢
