### ISSUE TITLE
1.0.1  -- App底部导航栏消失

### ISSUE THREAD

**Issue by weikjblue** [luckybilly/SmartSwipe#11]
SmartSwipe 1.0.1
红米5
Android版本8.1
底部导航栏消失
baseapplication 设置了仿微信侧滑
 1-- SmartSwipeBack.activitySlidingBack(this, null, 0,
                ContextCompat.getColor(this, R.color.transparent), 0x80000000.toInt(), 30, 0.5f, 1)
2-- 左侧  屏幕中间部分 正常  屏幕 上/下 1/3部分 遮罩白屏了

**Comment by luckybilly** [comment]
@weikjblue 贴一下截图吧

**Comment by weikjblue** [comment]
@luckybilly 问题找到了  因为之前项目引用了  https://github.com/ikew0ng/SwipeBackLayout 这个项目
两个项目冲突了  禁掉之后就没问题了 实在抱歉
