### ISSUE TITLE
Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by weikjblue** [luckybilly/SmartSwipe#15]
Only fullscreen opaque activities can request orientation
已经在项目中使用 目前在Android8.0(API 26)必现 
bugly记录了大量崩溃
不过貌似是源码的改动导致
https://zhuanlan.zhihu.com/p/32190223
http://www.manongjc.com/article/37655.html

**Comment by luckybilly** [comment]
你的项目中是不是使用了透明主题？  把它去掉。

SmartSwipeBack不需要透明主题， [如何兼容5.0以下版本？](https://qibilly.com/SmartSwipe-tutorial/pages/SmartSwipeBack.html#%E5%85%BC%E5%AE%B950%E4%BB%A5%E4%B8%8B%E7%B3%BB%E7%BB%9F%E7%89%88%E6%9C%AC)
