### ISSUE TITLE
关于activity背景色问题

### ISSUE THREAD

**Issue by AltriaTT** [luckybilly/SmartSwipe#16]
你好，我在Theme中给background设置一个颜色，在activitySlidingBack时不能显示上一个activity内容，只有当完全返回时才显示activity内容。

**Comment by luckybilly** [comment]
在demo中能复现吗？ 复现的代码麻烦提供一下

**Comment by luckybilly** [comment]
@AltriaTT 找到问题了：由于在theme中设置android:background后，会默认给所有的view都设置一个背景色，将SmartSwipeWrapper也设置了背景色，从而导致这个问题。

v1.0.4版本修复了这个问题
