### ISSUE TITLE
你好，引入依赖后报错

### ISSUE THREAD

**Issue by createBean** [luckybilly/SmartSwipe#17]
请问这种报错是什么原因？ 在app下的build.gradle下增加的依赖去同步后就报错了 
![image](https://upload-images.jianshu.io/upload_images/3794407-44d6a9ea40f57538.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by createBean** [comment]
minsdk已经是21的了

**Comment by luckybilly** [comment]
@createBean 抱歉，这个`latestVersion`让你产生误解了，它就是字面意思：最新版本， 当前的最新版本号在项目README文件的最顶部有介绍
具体到你引入的库，最新版本号是： [![Download](https://api.bintray.com/packages/hellobilly/android/smart-swipe/images/download.svg)](https://bintray.com/hellobilly/android/smart-swipe/_latestVersion)

**Comment by luckybilly** [comment]
@createBean 如果SmartSwipe对你有用的话，还请不吝点star支持一下哈
