### ISSUE TITLE
关于SpaceConsumer

### ISSUE THREAD

**Issue by atinysix** [luckybilly/SmartSwipe#19]
仔细对比了下QQ的OverScroll效果，发现在使用SpaceConsumer时，多次触发滑动事件，比如：连续上下两次滑动，会有动画阻塞的情况发生，稍微有点不流畅，希望能够优化下。

**Comment by luckybilly** [comment]
@daiwj 没有复现你说的动画阻塞的情况，能不能说得详细点，最好录制个视频

另外：QQ的OverScroll效果指的是哪个页面上的交互？

**Comment by atinysix** [comment]
手Q“动态”页面，当手指向上滑动时，突然释放，并且迅速向下滑动，页面会立马跟随手指方法滑动，但是SpaceConsumer的效果，在向上滑动时，突然释放并且迅速向下滑动后 界面就停止滑动了，并没有跟随第二次的滑动手势，大概就是这样的情况吧

**Comment by luckybilly** [comment]
明白你说的意思了，先说一下如何满足你这种需求：

```java
SmartSwipe.wrap(recyclerView)
    .addConsumer(new SpaceConsumer())
    .enableVertical()
    .setDisableSwipeOnSettling(true); //添加这一行
```

原因跟SmartSwipe的工作原理有关：

1. SmartSwipe是处理侧滑的，同一时间只有一个侧滑方向（上/下/左/右），当你向上滑动时，此时SwipeConsumer已经给它**定向**为bottom，在它被关闭前，一直为bottom。

2. SwipeConsumer默认情况下`mDisableSwipeOnSettling=false`，表示在动画平滑自动恢复时，down事件触发时，将捕获它成为当前侧滑方向的侧滑事件，从而实现中止动画并继续当前方向侧滑的效果。所以你第二次的滑动被捕获成为向上拉动的侧滑事件，而移动方向为向下，但向bottom方向的侧滑状态为**已关闭**，所以继续向下滑动仍然呈现为关闭状态。

3. 通过`consumer.setDisableSwipeOnSettling(true)`将`mDisableSwipeOnSettling`置为`true`之后，手指释放后第二次的滑动也就不会被捕获为当前侧滑方向（bottom方向的侧滑）

**Comment by atinysix** [comment]
试了下，第二次的滑动事件已经有响应了，但是还是会有第一次的回弹动画 和第二次瞬间滑动产生的fling冲突的情况，不知道能不能处理哈，因为项目有很多页面希望加个这个效果又不想嵌套个ScrollView，希望能优化哈，当然不优化也可以使用了。另外再尝试看你的源码，希望自己能改造下。

**Comment by luckybilly** [comment]
禁用SwipeOnSettling后，第一次的回弹肯定是要播放完的。

你说的fling冲突能详细描述一下么

**Comment by atinysix** [comment]
这个怎么说呢，我也很难去直接操作出来，算是很暴力的测试方式吧，我的操作是 先快速上拉，等页面执行回弹动画时，迅速下拉，现在的效果是，页面确实会往上走，但是中间的回弹动画还是强制回弹，导致回弹和fling冲突，动画会优先执行结束，卡一下，页面才往会滚动。我觉得不浪费你时间了，就这样吧，感谢解答了

**Comment by atinysix** [comment]
又看了下QQ的效果，好像QQ也会有这个卡一下的情况，可能这个本身就是个冲突的交互，不用优化了吧。再次感谢了，

**Comment by luckybilly** [comment]
感谢你对SmartSwipe的支持！ 如果方便的话，还请在[这里](https://github.com/luckybilly/SmartSwipe/issues/14) 添加一下你公司产品相关信息，这将成为新接触SmartSwipe还在观望的新用户的信心来源。 （当然，如果不方便也没关系，Anyway, Take it easy！）
