### ISSUE TITLE
Over

### ISSUE THREAD

**Issue by GreenVegetables** [luckybilly/SmartSwipe#20]

**Comment by luckybilly** [comment]
没有任何信息啊，老兄

**Comment by GreenVegetables** [comment]
作者的库很有用，关于OverScroll感觉有点不自然，就是fling到边缘的时候，会弹跳一下，希望这个弹跳的力度以及距离能自然一些，而不是每次都是固定模式的弹一下。如果作者有时间，可以优化下

**Comment by GreenVegetables** [comment]
> 没有任何信息啊，老兄

大哥，我手抖啊，直接提交了，这不是重新编辑来着吗

**Comment by luckybilly** [comment]
你说的这个overScroll指的是demo里封面上用的Interpolator吗？

**Comment by GreenVegetables** [comment]
> 你说的这个overScroll指的是demo里封面上用的Interpolator吗？

SpaceConsumer

**Comment by luckybilly** [comment]
能把你使用的代码贴一下吗

**Comment by GreenVegetables** [comment]
> 能把你使用的代码贴一下吗

就demo中的，侧边栏SpaceConsumer，列表中可以上下滚动到边缘观察

**Comment by luckybilly** [comment]
很抱歉，我没有复现你说的弹一下的问题

demo中点击侧边栏的SpaceConsumer跳转到的页面是SpaceConsumerActivity

页面中为recyclerView添加了SpaceConsumer
```java
SmartSwipe.wrap(recyclerView).addConsumer(new SpaceConsumer()).enableVertical();
```
下拉后释放，会自动动画平滑恢复，**是没有弹跳效果的**

对应的gif动图如下：
![SpaceConsumer](https://qibilly.com/SmartSwipe-tutorial/images/spaceConsumer.gif)

如果要控制动画相关的属性，可以设置：

1. 动画时长： `consumer.setMaxSettleDuration(ms)`
2. 插值器： `consumer.setInterpolator(interpolator)`
