### ISSUE TITLE
activitySlidingBack有的时候会不显示背后的activity而是纯色背景

### ISSUE THREAD

**Issue by coderfelixby** [luckybilly/SmartSwipe#21]
在1.04版本中：
application中初始化后，有时不能正确获取后面的activity
  SmartSwipeBack.activitySlidingBack(this, new SmartSwipeBack.ActivitySwipeBackFilter() {
            @Override
            public boolean onFilter(Activity activity) {
                return !(activity instanceof MainActivity);
            }
        });

麻烦帮着看下要怎么解决呢？应用主题不是透明的。

**Comment by luckybilly** [comment]
@Felexby “有时不能正确获取后面的activity”具体是下列情况中的哪种？
- 同一个activity有时能透明显示，有时不能？
- 多个activity，有的能透明，有的不能？
- 不同设备，有的能透明，有的不能？

**Comment by coderfelixby** [comment]
同一个activity有时能透明显示，有时不能？

**Comment by coderfelixby** [comment]
稍等 我录制份gif给您

**Comment by luckybilly** [comment]
请问你项目中是否用了其它侧滑返回库？比如：SwipeBackLayout
issue #11 中的第二个问题就是同时用了SmartSwipeBack和 SwipeBackLayout导致的显示纯色

![image](https://user-images.githubusercontent.com/4155835/62507905-63968900-b838-11e9-8559-640238236063.png)

**Comment by coderfelixby** [comment]
并没有使用，[目前出现的问题,有时候好有时候坏~](https://object.renchengqi.com/test/20190806_105638.gif)

**Comment by luckybilly** [comment]
加一下QQ吧： 532493721

**Comment by coderfelixby** [comment]
已加~

**Comment by luckybilly** [comment]
> 已加~

没有看到哦， 是不是号码弄错了呢？

**Comment by coderfelixby** [comment]
有申请，我的QQ是306026450
