### ISSUE TITLE
已经引用了下拉刷新库，编译报错

### ISSUE THREAD

**Issue by ghost** [luckybilly/SmartSwipe#22]
AAPT: error: duplicate value for resource 'attr/layout_gravity' with config

**Comment by luckybilly** [comment]
@blackberry2016 把你的使用方式代码贴一下吧，不然信息太少没办法帮到你。

**Comment by jqorz** [comment]
我也遇到了，1.0.3版本和1.0.4版本都会编译报错。
`implementation 'com.billy.android:smart-swipe:1.0.3'`
只要引用，一行代码没写都会编译报错
`  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\user\.gradle\caches\transforms-2\files-2.1\0ef7469031a601aeae39c8d21cd315fb\res\values\values.xml:173:5-160: AAPT: error: duplicate value for resource 'attr/layout_gravity' with config ''.`

**Comment by luckybilly** [comment]
@jqorz @blackberry2016 已升级到1.0.5，烦请验证一下是否已修复此问题！

修复方式的[参考来源](https://stackoverflow.com/questions/47668526/duplicate-value-for-resource-attr-font-with-config)

**Comment by jqorz** [comment]
> @jqorz @blackberry2016 已升级到1.0.5，烦请验证一下是否已修复此问题！
> 
> 修复方式的[参考来源](https://stackoverflow.com/questions/47668526/duplicate-value-for-resource-attr-font-with-config)

已经可以正常编译了。感谢及时修复

**Comment by luckybilly** [comment]
@jqorz @blackberry2016 感谢你们
