### ISSUE TITLE
关于上拉drawConsumer问题咨询

### ISSUE THREAD

**Issue by showdown-zhou** [luckybilly/SmartSwipe#26]
你好我用drawConsumer里面嵌套了一个NestedScrollView 但是上拉有时候NestedScrollView不滚动然后抽屉下面会出现一段空白被网上拉出来了一部分，请问怎么处理？如图
![QQ图片20190809175020](https://user-images.githubusercontent.com/39110520/62770717-2ba87380-bace-11e9-944f-4fed7808ea74.jpg)

**Comment by luckybilly** [comment]
能在demo上复现一下吗？

demo首页的布局文件`activity_main.xml`中用到了ScrollView（横屏的时候首页可以滚动），你可以将它改成NestedScrollView，然后在MainActivity中改成你现在的用法，试试能不能复现出你说的问题。

![image](https://user-images.githubusercontent.com/4155835/62772854-39acc300-bad3-11e9-8934-ae67210a5cf8.png)

**Comment by showdown-zhou** [comment]
你好，我刚在demo上操作了下，就是下面这部分白色的。可能我的视图嵌套比较多所以有的时候我想触发NestedScrollView的滚动，但是抽屉会被往上拉，先出发了抽屉的事件。可以把抽屉视图的事件直接传递到子布局嘛。就是关闭抽屉已经显示出来的上，下面不留白
![QQ图片20190809183926](https://user-images.githubusercontent.com/39110520/62773565-08cd8d80-bad5-11e9-809d-212b2cfa2da3.jpg)

**Comment by luckybilly** [comment]
@showdown-zhou 

> 你好，我刚在demo上操作了下，就是下面这部分白色的

你截图中的这个白色效果是demo里嵌套了一个`SpaceConsumer`，是正常的，【[代码](https://github.com/luckybilly/SmartSwipe/blob/ed375f2faf08f1328afdaa5da283c4440d9c8296/app/src/main/java/com/billy/android/swipe/demo/MainActivity.java#L117)】

这个问题看起来有点像以下2种情况导致：
1. 调用了`consumer.setOpenDistance(distance)`：distance大于抽屉的height
2. 调用了`consumer.setOverSwipeFactor(factor)`: factor大于0

把你使用的代码贴一下吧，方便排查

**Comment by showdown-zhou** [comment]
> @showdown-zhou
> 
> > 你好，我刚在demo上操作了下，就是下面这部分白色的
> 
> 你截图中的这个白色效果是demo里嵌套了一个`SpaceConsumer`，是正常的，【[代码](https://github.com/luckybilly/SmartSwipe/blob/ed375f2faf08f1328afdaa5da283c4440d9c8296/app/src/main/java/com/billy/android/swipe/demo/MainActivity.java#L117)】
> 
> 这个问题看起来有点像以下2种情况导致：
> 
> 1. 调用了`consumer.setOpenDistance(distance)`：distance大于抽屉的height
> 2. 调用了`consumer.setOverSwipeFactor(factor)`: factor大于0
> 
> 把你使用的代码贴一下吧，方便排查

你好，问题找到了就是下面那个站位的SpaceConsumer导致的。SpaceConsumer是透明的
