### ISSUE TITLE
文档上的代码和实际效果不一样呀

### ISSUE THREAD

**Issue by leielyq** [luckybilly/SmartSwipe#28]
rt。

**Comment by luckybilly** [comment]
比如说？

**Comment by leielyq** [comment]
//activity侧滑返回
        SmartSwipe.wrap(this)
                .addConsumer(new ActivitySlidingBackConsumer(this))
                .setRelativeMoveFactor(0.5F)
                .enableLeft();
文档是这样的，但是实际上  加入 SmartSwipeBack.activitySlidingBack(this, null);才能使背景Activity跟随滑动。
还有  
//侧滑删除
        SmartSwipe.wrap(mPhoto)
                .addConsumer(new TranslucentSlidingConsumer())
//                .enableHorizontal() //启用左右两侧侧滑
                .enableVertical()//启用上下两侧侧滑
                .addListener(new SimpleSwipeListener(){
                    @Override
                    public void onSwipeOpened(SmartSwipeWrapper wrapper, SwipeConsumer consumer, int direction) {
                        //侧滑打开时，移除
//                        ViewParent parent = wrapper.getParent();
//                        if (parent instanceof ViewGroup) {
//                            ((ViewGroup) parent).removeView(wrapper);
//                        }
                        mFloatView.dismiss();
                        //adapter.removeItem(getAdapterPosition());// 也可用作从recyclerView中移除该项
                    }
                });
这个是文档的，实际上的透明过度效果没有看出用哪个方法完成

**Comment by luckybilly** [comment]
### 1. 关于侧滑返回
```java
//activity侧滑返回
SmartSwipe.wrap(this)
.addConsumer(new ActivitySlidingBackConsumer(this))
.setRelativeMoveFactor(0.5F)
.enableLeft();
```
这段示例代码来自[ActivitySlidingBackConsumer介绍页](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/ActivitySlidingBackConsumer.html#%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81)，文档中明确说明了它是`专为完成Activity的侧滑而做的一种效果`，在该页面中主要是介绍如何使用ActivitySlidingBackConsumer的。

SmartSwipeBack是SmartSwipe中为侧滑返回而封装的工具类，其中封装了使用不同的侧滑返回相关的consumer来实现全局侧滑返回效果，具体说明文档[点这里](https://qibilly.com/SmartSwipe-tutorial/pages/SmartSwipeBack.html)

两者之间区别是：具体的某个activity侧滑返回效果（如：ActivitySlidingBackConsumer）需要在activity（或baseActivity）中调用，而SmartSwipeBack是可以全局设置，使用更方便。SmartSwipeBack的特点在文档首页最上方就有介绍：

![image](https://user-images.githubusercontent.com/4155835/62919903-a6c39f80-bdd6-11e9-9619-80850326565c.png)

看文档需要仔细哦！

### 2. 关于侧滑删除
>这个是文档的，实际上的透明过度效果没有看出用哪个方法完成

你贴出来的代码是演示使用`TranslucentSlidingConsumer`来做侧滑删除效果的，[文档](https://qibilly.com/pages/consumers/pages/consumers/TranslucentSlidingConsumer.html)中的gif动图上也有演示（*另外还演示了用它做出的下拉关闭效果*），

TranslucentSlidingConsumer的侧滑效果是：侧滑后可显示被其遮挡的view

**不明白你的问题的什么**

**Comment by leielyq** [comment]
1. 原来直接调用SmartSwipeBack即可，谢谢

2. ### TranslucentSlidingConsumer的侧滑效果是：侧滑后可显示被其遮挡的view 
我看gif上是有透明度的变化的，实际使用该代码没有透明度变化，只是单纯的位移

3.希望能支持一下PopupWindow

**Comment by luckybilly** [comment]
> 2. 我看gif上是有透明度的变化的，实际使用该代码没有透明度变化，只是单纯的位移

你说的透明度变化应该是gif中演示的大图下拉关闭的效果吧？ 那是demo中实现的配合TranslucentSlidingConsumer的一种稍复杂的用法（在listener.onSwipeProcess方法中根据progress设置透明度），[代码](https://github.com/luckybilly/SmartSwipe/blob/018986bbbdbb9e31eb4ff72bc59fe778057e1421/app/src/main/java/com/billy/android/swipe/demo/consumer/ImageViewerActivity.java#L60)

另外，TranslucentSlidingConsumer也是可以设置遮罩颜色和边缘颜色效果的，如下所示：

```java
SwipeConsumer consumer = SmartSwipe.wrap(view)
    .addConsumer(new TranslucentSlidingConsumer())
    .setScrimColor(0x4f000000)  //设置遮罩颜色，侧滑过程中遮罩颜色将会从0x4f000000 渐变到 0x00000000
    .setShadowColor(0x7fff0000) //设置边缘，侧滑过程中边缘颜色将会从0x7fff0000 渐变到 0x00ff0000
    .showScrimAndShadowOutsideContentView() //遮罩和边缘阴影显示在contentView之外（即拖动后的空间）
//  .showScrimAndShadowInsideContentView() //遮罩和边缘阴影显示在contentView区域
    .enableHorizontal()
    ;
```
效果如下：

//showScrimAndShadowOutsideContentView()

![image](https://user-images.githubusercontent.com/4155835/62952026-8ff46b80-be1d-11e9-9726-6b4df71d9a91.png)

//showScrimAndShadowInsideContentView()

![image](https://user-images.githubusercontent.com/4155835/62952210-d6e26100-be1d-11e9-9fcf-be66429dabbe.png)



>3.希望能支持一下PopupWindow

SmartSwipe是专门用来处理侧滑的框架，什么样的需求需要支持PopupWindow呢？

**Comment by luckybilly** [comment]
另外，consumer有很多属性可以设置，具体的请仔细查看文档，可以通过修改demo的代码配置不同的参数来体验其效果。 [文档：公共属性](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/common_settings.html)， 除了公共属性之外，有些consumer还有自己独有的一些属性设置，详情请查看各consumer的文档
