### ISSUE TITLE
手势滑动时，边缘阴影可以设置不显示？

### ISSUE THREAD

**Issue by JasonLian2020** [luckybilly/SmartSwipe#29]
作者，你好。 @luckybilly 

- 依赖版本：smart-swipe 1.0.6

- 背景：
现在我项目里面使用的是BottomSheetDialog，不够解耦。
所以想用Activity来实现从下弹出，手势下滑跟随滑动关闭。
因为UI的效果，只是需要手势下滑跟随滑动关闭就行，所以不想要边缘阴影。

**Comment by luckybilly** [comment]
@tomUp 可如下设置：

```java
consumer
.setShadowSize(0)//设置边缘阴影的size
.setShadowColor(Color.TRANSPARENT)//设置边缘阴影的颜色值
.setScrimColor(Color.TRANSPARENT)//设置玻璃遮罩的颜色值
```

**Comment by JasonLian2020** [comment]
@luckybilly 不好意思，API没看仔细~
