### ISSUE TITLE
关于侧滑菜单的问题

### ISSUE THREAD

**Issue by coderfelixby** [luckybilly/SmartSwipe#31]
### 问题描述

请描述您遇到的问题
 我想禁止侧滑菜单通过侧滑展开，只能通过actionbar上的按钮控制要怎么操作呢？
- 预期行为：
禁止侧滑菜单打开
- 实际行为：
无效
### 出问题的代码
我在点击按钮展开view的时候再处理addConsumer方法，但是无法实现相应侧滑返回的功能

**Comment by luckybilly** [comment]
@Felexby 这需要用到[lock](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/common_settings.html#1-%E4%BE%A7%E6%BB%91%E6%96%B9%E5%90%91%E7%9A%84%E5%90%AF%E7%94%A8%E4%B8%8E%E9%94%81%E5%AE%9A)

请按如下设置：

```java
//设置侧滑菜单后，将其lock住（不能手势拖动）
SwipeConsumer consumer = SmartSwipe.wrap(rootView)
    .addConsumer(new DrawerConsumer())
    .setLeftDrawerView(menuView) //添加左侧侧滑菜单
    .lockLeft() // 禁用手动侧滑(但可以通过代码触发打开和关闭)
    ;

//后面可以通过consumer对象来操作打开和关闭

consumer.smoothLeftOpen(); //动画打开
consumer.setLeftOpen(); //瞬间打开
consumer.smoothClose(); //动画关闭
consumer.close(); //瞬间关闭
```

在demo中可以在MainActivity中给`mDrawerConsumer`或`mSlidingConsumer`设置lock来验证效果。

PS：SmartSwipe中关于侧滑的很多功能都支持通过属性设置来完成，由于内容过多，我在推广的文章中没有一一介绍，但在项目文档中均作了说明，更多属性介绍请查看[文档中的公共属性](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/common_settings.html)

重要的事情说三遍：一定要[多看文档](https://qibilly.com/SmartSwipe-tutorial/)，[多看文档](https://qibilly.com/SmartSwipe-tutorial/)，[多看文档](https://qibilly.com/SmartSwipe-tutorial/)

如果看文档仍然无法解决问题，欢迎提issue咨询！ : )

**Comment by coderfelixby** [comment]
问题已解决，十分感谢
