### ISSUE TITLE
关于侧滑菜单

### ISSUE THREAD

**Issue by coderfelixby** [luckybilly/SmartSwipe#32]
### 问题描述

侧滑菜单展开时可以点击后面的activity,后面的控件还能接受点击事件
- 预期行为：
后面activity不再响应事件
- 实际行为：
现在后面的activity还能响应点击事件
### 出问题的代码
```java
       mSwipeConsumer.smoothLeftOpen();正常展开后mainactivity还能捕捉到点击事件

```

### 当前使用的SmartSwipe版本号：
1.0.4

### 截图或gif
![gif截图](https://user-images.githubusercontent.com/23166789/63085450-2476df00-bf80-11e9-82ac-2d862702721c.gif)

**Comment by luckybilly** [comment]
@Felexby 从gif图中没看到你点的是哪个控件
猜测你是点击半透明区域，但是，我在demo的MainActivity中没有复现你说的情况
使用代码贴一下吧，如果在demo中能复现，请说明一下复现方式

**Comment by luckybilly** [comment]
@Felexby 我想我大概明白你的意思了，应该是你的侧滑菜单的点击穿透。

将你的菜单控件设置： `setClickable(true)`即可

**Comment by coderfelixby** [comment]
> @Felexby 我想我大概明白你的意思了，应该是你的侧滑菜单的点击穿透。
> 
> 将你的菜单控件设置： `setClickable(true)`即可

那样会影响侧向晃动么

**Comment by luckybilly** [comment]
@Felexby 并不会，你试试就知道了

另外，如果这个项目对你有帮助，还请star支持一下 : )

**Comment by coderfelixby** [comment]
已经star了，十分感谢~
