### ISSUE TITLE
How to use Smart Swipe inside fragments?

### ISSUE THREAD

**Issue by ghost** [luckybilly/SmartSwipe#35]

**Comment by luckybilly** [comment]
@rajatpundir could you please tell me more about your feature?

- If you want to wrap a view inside the fragment, that's the same as inside an activity:
```java
SmartSwipe.wrap(...)		//view
	.addConsumer(...)	//add a SwipeConsumer
	.enableDirection(...) 	//Specifies which side of the slide the SwipeConsumer will consumes
	.setXxx(...)		//[optional] some other Settings
	.addListener(...); 	//[optional] add listener(s) to the SwipeConsumer
```
- If you want to wrap the fragment rootView, return `consumer.getWrapper()` instead of `return rootView` within `onCreateView`
```java
public class MyFragment extends Fragment {
    //...
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
         //rootView = ....
        return  SmartSwipe.wrap(rootView) //wrap the fragment rootView 
		.addConsumer(...) 	//add a SwipeConsumer
		.enableDirection(...) 	//Specifies which side of the slide the SwipeConsumer will consumes
		.setXxx(...) 		//[optional] some other Settings
		.addListener(...) 	//[optional] add listener(s) to the SwipeConsumer
		.getWrapper();//instead of rootView
    }
    //...
}
```

- If you want to add sliding back gesture to fragment, you can wrap the fragment's container.

> [BezierBackConsumer](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/BezierBackConsumer.html) and [StayConsumer](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/StayConsumer.html) will be helpful.

```java
SmartSwipe.wrap(container)	//view
	.addConsumer(...)	//add a SwipeConsumer
	.enableDirection(...) 	//Specifies which side of the slide the SwipeConsumer will consumes
	.setXxx(...)		//[optional] some other Settings
        .addListener(new SimpleSwipeListener() {
            @Override
            public void onSwipeOpened(SmartSwipeWrapper wrapper, SwipeConsumer consumer, int direction) {
                if (fragmentManager.getBackStackEntryCount() > 0) {
                    fragmentManager.popBackStack();
                }
            }
        });
```

> Additionally, you can extend [SwipeConsumer](https://github.com/luckybilly/SmartSwipe/blob/master/smart-swipe/src/main/java/com/billy/android/swipe/SwipeConsumer.java) to create your own swipe effects, and use them as same as consumers within SmartSwipe(eg. [SpaceConsumer](https://github.com/luckybilly/SmartSwipe/blob/master/smart-swipe/src/main/java/com/billy/android/swipe/consumer/SpaceConsumer.java) ).

**Comment by ghost** [comment]
Thanks, I was able to get SmartSwipe to work with your examples. I can add the Smart Swipe to a RecyclerView which is inside a LinearLayout which is inside a fragment. But when I add SmartSwipe to LinearLayout, it doesn't seem to work and SmartSwipe says it requires an Activity or View to work correctly.

I could not get SmartSwipe to work with fragment's ViewGroup container or by returning a wrapper from fragment's onCreateView. Please note that my use case involves highly nested fragments.

But Linear Layout extends View Group which extends View and I thought Smart Swipe should work with this? This should be enough for me.
