### ISSUE TITLE
contentView的高度不固定，使用SlidingConsumer不能填充为内容高度或父高度

### ISSUE THREAD

**Issue by oneapp1e** [luckybilly/SmartSwipe#36]
### 问题描述
contentView的高度不固定，使用SlidingConsumer不能填充为内容高度或父高度，使用demo把固定高度去除，就能看出来问题。

- 预期行为：
期望能够填充为父控件或者内容区域的高度。

### 当前使用的SmartSwipe版本号：
 **1.0.6**

![Screenshot_2019-08-21-18-49-54-186_com billy android swipe demo](https://user-images.githubusercontent.com/4979372/63426433-60f57f80-c445-11e9-9161-5900321af47a.jpg)
![Screenshot_2019-08-21-18-50-17-966_com billy android swipe demo](https://user-images.githubusercontent.com/4979372/63426443-681c8d80-c445-11e9-8b6a-e149cc820e51.jpg)

**Comment by luckybilly** [comment]
hi, @oneapp1e

**Comment by luckybilly** [comment]
hi, @oneapp1e 

> 预期行为：
> 期望能够填充为父控件或者内容区域的高度。

这个预期行为与SlidingConsumer添加drawerView（抽屉）的设计思路不一致哦，添加一个drawerView的大致设计思路（[源码](https://github.com/luckybilly/SmartSwipe/blob/e22d1a378f119804d6e7d100ee5c313038a4ea3b/smart-swipe/src/main/java/com/billy/android/swipe/consumer/DrawerConsumer.java#L385)）是：如果drawerView**设置了布局参数**(layoutParams)，则将它直接添加到SmartSwipeWrapper中，**否则**将为它创建一个**默认的布局参数**(layoutParams)，宽高属性设置如下：
- 侧滑方向属性为：WRAP_CONTENT（如：左侧的抽屉，宽度为WRAP_CONTENT）
- 非侧滑方向属性为：MATCH_PARENT（如：左侧的抽屉，高度为MATCH_PARENT）

> PS：这个逻辑是在DrawerConsumer中实现的，SlidingConsumer继承了DrawerConsumer

所以，在你贴图的demo中修改的2处将layoutParams的高度由MATCH_PARENT改为WRAP_CONTENT后，侧滑菜单的高度也就不会自动充满父控件

**Comment by oneapp1e** [comment]
layout_item_view.xml  我只是把item内容区域的高度原来写死的80dp，改成wrap_content。
activitiy_main.xml 中的      <com.billy.android.swipe.SmartSwipeWrapper
                    android:id="@+id/main_ui_wrap_view"
                    android:layout_width="match_parent"
                    android:layout_height="100dp"
                    android:background="@drawable/menu_item_bg"
            >  固定高度100dp改为wrap_content


我要实现的就是非侧滑方向  MATCH_PARENT

**Comment by luckybilly** [comment]
@oneapp1e 是自定义ViewGroup的onMeasure方法逻辑不完善，v1.0.7修复了这个问题，烦请验证！

**Comment by oneapp1e** [comment]
v1.0.7 已经验证没有问题了
