### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by oneapp1e** [luckybilly/SmartSwipe#37]
### 问题描述

1 com.billy.android.swipe.internal.b.b(SourceFile:823)
--
2 com.billy.android.swipe.SmartSwipeWrapper.onTouchEvent(SourceFile:81)
3 android.view.View.dispatchTouchEvent(View.java:12527)
4 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
5 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
6 com.billy.android.swipe.SmartSwipeWrapper.dispatchTouchEvent(SourceFile:60)
7 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
8 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
9 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
10 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
11 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
12 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
13 android.app.Activity.dispatchTouchEvent(Activity.java:3465)
14 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
15 android.view.View.dispatchPointerEvent(View.java:12768)
16 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5230)
17 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5030)
18 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
19 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
20 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
21 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4704)
22 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
23 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4761)
24 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
25 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
26 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
27 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
28 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
29 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7263)
30 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7232)
31 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7193)
32 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7369)
33 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
34 android.os.MessageQueue.nativePollOnce(Native Method)
35 android.os.MessageQueue.next(MessageQueue.java:326)
36 android.os.Looper.loop(Looper.java:165)
37 android.app.ActivityThread.main(ActivityThread.java:6810)
38 java.lang.reflect.Method.invoke(Native Method)
39 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
40 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### 出问题的代码

使用的代码
```java
  SmartSwipeBack.activitySlidingBack(this, new SmartSwipeBack.ActivitySwipeBackFilter() {
            @Override
            public boolean onFilter(Activity activity) {
                //根据传入的activity，返回true代表需要侧滑返回；false表示不需要侧滑返回
                return !(activity instanceof VZyMainActivity);
            }
        });

```

### 当前使用的SmartSwipe版本号：
**1.0.6**

线上产品使用后，上报的错误。

**Comment by oneapp1e** [comment]
https://github.com/luckybilly/SmartSwipe/issues/36#issuecomment-523774380
另外回复一下我这个问题。

**Comment by luckybilly** [comment]
@oneapp1e v1.0.7修复了这个问题

**Comment by oneapp1e** [comment]
新版本使用v1.0.7没有问题了
