### ISSUE TITLE
你好，非常感谢阁下的库。刚在做侧滑删除功能时，参考你的SlidingConsumerActivity，配合RecyclerView使用时，拿到viewHolder.itemView之后设置setOnClickListener无效果

### ISSUE THREAD

**Issue by leguang** [luckybilly/SmartSwipe#44]
你好，非常感谢阁下的库。刚在做侧滑删除功能时，参考你的SlidingConsumerActivity，配合RecyclerView使用时，拿到viewHolder.itemView之后设置setOnClickListener无效果

我的demo中是以BaseRecyclerViewAdapterHelper作为adepter的，其中拿到viewHolder.itemView后设置setOnClickListener，然后设置相关单击监听无效果。

我将你demo中的BaseRecyclerViewActivity中的
```
 ((View)ivAvatar.getParent()).setOnClickListener(new View.OnClickListener() {
     @Override
     public void onClick(View v) {
         if (data != null) {
             Intent intent = new Intent(BaseRecyclerViewActivity.this, ImageViewerActivity.class);
             intent.putExtra(ImageViewerActivity.IMAGE_EXTRA, data.avatar);
             startActivity(intent);
         }
     }
 });
````
都注释掉，然后再加上
```
 itemView.setOnClickListener(new OnClickListener() {
     @Override
     public void onClick(View v) {
         Toast.makeText(SlidingConsumerActivity.this, "单击了itemView", Toast.LENGTH_SHORT).show();
     }
 });
```
仍然没有点击效果。
是不是因为你的拖拽事件或者其他说明因素影响了点击事件的分发？

**Comment by luckybilly** [comment]
@leguang 
你所遇到问题的原因是： viewHolder中itemView此时为`SmartSwipeWrapper`对象，而`SmartSwipeWrapper`本身只处理侧滑相关手势事件，不支持点击、长按等事件，因为**这些事件应该都是应该设置到contentView上**的。

可以通过`SmartSwipeWrapper.getContentView()`来获取contentView

**Comment by leguang** [comment]
明白
