### ISSUE TITLE
提问：如何暂停手势

### ISSUE THREAD

**Issue by pys200603027** [luckybilly/SmartSwipe#45]
### 问题描述

请描述您遇到的问题

- 预期行为：暂停返回手势，解决手势冲突

- 实际行为：

你好作者，请问是有暂停手势的API调用嘛，需要在某种时刻暂停下手势

**Comment by luckybilly** [comment]
可以用[lockXxx() / unlockXxx()](https://qibilly.com/SmartSwipe-tutorial/pages/consumers/common_settings.html#1-%E4%BE%A7%E6%BB%91%E6%96%B9%E5%90%91%E7%9A%84%E5%90%AF%E7%94%A8%E4%B8%8E%E9%94%81%E5%AE%9A)

**Comment by pys200603027** [comment]
好的多谢指点
