### ISSUE TITLE
只想要 activity 侧滑返回该调用哪个版本呢？

### ISSUE THREAD

**Issue by 1277379283** [luckybilly/SmartSwipe#46]
### 问题描述

请描述您遇到的问题

- 预期行为：

- 实际行为：

### 出问题的代码

```java
//由于SmartSwipe中有较多的内置SwipeConsumer及较多的属性设置
// 为方便排查，请在这里将您出现问题的代码展示出来

```

### 当前使用的SmartSwipe版本号：
例如： **1.0.6**

### 截图或gif

(提交issue前请删除本行文字)有时候，一图胜千言，为了更高效的沟通，请将您认为有助于说明问题的截图或者gif图片贴在此处吧！

>>>>>>>>>>>>>>  提交issue前请删除以下内容  <<<<<<<<<<<<<<<

=========== 小贴士 ============

将图片贴到issue中有以下几种方式：

1. 复制图片后，在issue文本输入框中Ctrl + V (mac: command + V)粘贴，github会自动上传图片并添加为其markdown格式
2. 从文件夹中拖动图片到issue的文本输入框中，效果同上
3. 如果是一个在线图片，可在issue输入框中输入图片地址，markdown格式为： ![图片的描述](图片的地址)

**Comment by luckybilly** [comment]
@1277379283 你好，使用最新版就行。
内置的那些consumers没有单独拆分出来，是因为一方面它们大多数都很小，只有1个类文件而已；另一方面代码混淆时没有用到的类是会不会打包到dex中去的，不会影响包大小。

**Comment by 1277379283** [comment]
嗯嗯，好的，感谢你的讲解~

**Comment by zhaoxiuyu** [comment]
有混淆配置吗
