### ISSUE TITLE
嵌套在CoordinatorLayout中会导致滑动分发很混乱，但是使用SmartRefresh的lib不会

### ISSUE THREAD

**Issue by Khaos116** [luckybilly/SmartSwipe#48]
### 问题描述
AndroidX使用类似微博个人主页效果时，嵌套CoordinatorLayout+AppBarLayout+CollapsingToolbarLayout+MaterialToolbar+ViewPager+SmartSwipeRefresh+RecyclerView内部下拉刷新，出现滑动分发混乱(尤其是上滑动的时候，不触发header的向上滚动)

### 当前使用的SmartSwipe版本号：
Androidx的版本com.billy.android:smart-swipe:1.0.0

### SmartSwipeRefresh的截图(使用安卓X)
![GIF1](https://user-images.githubusercontent.com/11989916/69054311-db7e6d00-0a3d-11ea-8a20-b2ceaae20e4e.gif)

### SmartRefreshLayout的截(没有使用安卓X)
![GIF2](https://user-images.githubusercontent.com/11989916/69054766-e685cd00-0a3e-11ea-9a32-1fc36cbf1c3b.gif)

**Comment by luckybilly** [comment]
需要支持嵌套滑动，有没有加上下面这个依赖： 
```groovy
implementation 'com.billy.android:smart-swipe-support:1.0.0'
```
另外， 主库smart-swipe当前最新版本号为：[![Download](https://api.bintray.com/packages/hellobilly/android/smart-swipe/images/download.svg)](https://bintray.com/hellobilly/android/smart-swipe/_latestVersion)

**Comment by Khaos116** [comment]
@luckybilly 好的，我试试，感谢大佬

**Comment by Khaos116** [comment]
@luckybilly 
  api 'com.billy.android:smart-swipe:1.0.8'
  api 'com.billy.android:smart-swipe-support:1.0.0'
我改为了这两个，还是存在滑动问题呢，大佬，是不是需要有特殊用法呢?
不仅仅简单的：SmartSwipeRefresh.translateMode(shequChildRecycler, false)这样？

**Comment by luckybilly** [comment]
@caiyoufei  抱歉，你用的是androidX，应该用这个：
```groovy
implementation 'com.billy.android:smart-swipe-x:1.0.0'
```
如果还是有问题，可以把出问题的代码在你的[ABase](https://github.com/caiyoufei/ABase)项目中复现出来，这样我就可以clone下来排查问题了。

**Comment by Khaos116** [comment]
@luckybilly 大佬，我已经把效果提取到demo中了，可以帮忙看下
https://github.com/caiyoufei/CoordinatorSwipe

**Comment by luckybilly** [comment]
@caiyoufei 在1.1.0版本中解决了这个问题，烦请验证！
```
implementation 'com.billy.android:smart-swipe:1.1.0'
//compat for android x
implementation 'com.billy.android:smart-swipe-x:1.1.0'
```

**Comment by Khaos116** [comment]
@luckybilly 好的，感谢大佬

**Comment by Khaos116** [comment]
我的手机上没发现问题，应该好了，再次感谢大佬
