### ISSUE TITLE
使用之后为啥顶部标题栏不见了。。。

### ISSUE THREAD

**Issue by LvslGit** [luckybilly/SmartSwipe#69]
使用之后为啥顶部标题栏不见了。。。

**Comment by luckybilly** [comment]
我也不知道  [请看这里](https://www.baidu.com/s?ie=utf-8&cl=2&medium=0&rtt=1&bsst=1&tn=news&word=%E6%8F%90%E9%97%AE%E7%9A%84%E8%89%BA%E6%9C%AF&rsv_sug3=9&rsv_sug4=771&rsv_sug1=8&oq=%E6%8F%90%E9%97%AE%E7%9A%84&rsv_sug2=0&f=3&rsp=3&rsv_dl=news_t_sug&inputT=4688)
